2020-09-06 17:33:26,651 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-07 20:56:00,370 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-07 21:06:27,337 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-07 22:17:22,471 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-07 22:34:20,983 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:04:17,825 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:35:58,015 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:36:03,080 ERROR: Exception on / [GET] [in /home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/karomag/PycharmProjects/microblog/app/routes.py", line 52, in index
    prev_url=prev_url,
UnboundLocalError: local variable 'prev_url' referenced before assignment
2020-09-08 21:36:57,782 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:37:39,224 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:40:42,113 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:41:03,963 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:41:27,918 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:42:00,937 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:42:41,282 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:43:19,810 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:43:34,232 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:44:20,773 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 21:49:46,130 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-08 22:03:27,408 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-09 22:21:57,293 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:29:59,465 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:35:36,213 ERROR: Exception on /reset_password_request [POST] [in /home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/karomag/PycharmProjects/microblog/app/routes.py", line 228, in reset_password_request
    send_password_reset_email(user)
  File "/home/karomag/PycharmProjects/microblog/app/email.py", line 38, in send_password_reset_email
    text_body=render_template(
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2020-09-10 23:37:17,104 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:37:36,714 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
